spring:
  application:
    name: generator


com:
  mario:
    kafka:
      order-topic: "orders"
      bootstrap-servers:
        - localhost:9091
        - localhost:9092
        - localhost:9093
      security-protocol: "PLAINTEXT"

server:
  port: 8081
