com:
  mario:
    kafka:
      order-topic: "orders"
      order-full-topic: "orders-full"
      valuable-customer: "valuable-customer"
      valuable-customer-threshold: 4000
      full-mini-cart: "full-mini-cart"
      half-full-cart: "half-full-cart"
      bootstrap-servers:
        - localhost:9091
        - localhost:9092
        - localhost:9093
      security-protocol: "PLAINTEXT"
      application-id: "transformer"
      consumer-group-id: "transformer-group"
      trusted-packages: "*"
      api-endpoint: http://kafka.com/api/transaction/

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: kafka
    password: kafka